#!/bin/bash
# 本脚本用于对源代码中的函数名及全局变量名进行混淆，生成映射文件

# usage: rand a b
# 生成[a, b)之间的随机数
function rand(){
    min=$1
    max=$(($2-$min))
    num=$(($RANDOM+1000000000))
    echo $(($num%$max+$min))
}

# 生成随机字符
function rand_c() {
    base="qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM_$"
    echo ${base:$(rand 0 54):1}
}

# 生成16-32长度的随机变量名
function rand_s() {
    symbol=""
    for i in $(seq $(rand 16 33)); do
        symbol=$symbol$(rand_c)
    done
    echo $symbol
}

file=$2
src=$1

# 生成文件头，注释
cat > $file << EOF
//
//  $file
//

/*
 * This is the symbol substitution mapping file.
 * Auto-generated by $0, from the source file $src.
 * You can change the value of macro defination freely, but DO NOT DELETE any of them.
 */

EOF

# 提取源文件中所有的SYMBOL(_xxx)宏，并生成随机标识符
cat $src | sed -n "s/.*SYMBOL(\(_.*\)).*/\1/p" | while read symbol
do
    rand_symbol=`rand_s`
    echo -e "\033[32m$symbol\033[m -> \033[33m$rand_symbol\033[m"
    echo "#define $symbol \"$rand_symbol\"" >> $file
done

exit